export const API_KEYS = {
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  FETCH_USER: "FETCH_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
};

export const MODAL_KEYS = {
  LOGIN_MODAL: "LOGIN_MODAL",
  REGISTER_MODAL:"REGISTER_MODAL"
};
